## ========================================================================
##
## Things to READ
## --------------
##
##    This file will setup the STATIC Configuration options in Traefik
##
## ========================================================================

---
global:
  checkNewVersion: true
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: frontend
    watch: true