  certificatesResolvers:
    cloudflare:
      acme:
        email: myemail@domain.com
        storage: /var/traefik.certs/cloudflare-acme.json
        caServer: 'https://acme_v02.api.letsencrypt.org/directory'
        keyType: EC256
        dnsChallenge:
          provider: cloudflare
          resolvers:
            - "1.1.1.1:53"
            - "8.8.8.8:53"
